In [1]:
#import statistical libraries
import math
import statistics
import numpy as np
import pandas as pd

In [2]:
statistics.mean([4,3,7,6,5,2])

4.5

In [14]:
statistics.mode([20,15,12,17,18,15,20,20,15])

20

In [ ]:
statistics.multimode([20,15,12,17,18,15,20,20,15])

In [6]:
from decimal import Decimal as D
statistics.mean([D("0.5"), D("0.75"), D("0.625"),D("0.375")])

Decimal('0.5625')

In [10]:
data= ([7,3,6,5,2,1])
statistics.median_high(data)

5

In [11]:
data= ([4,3,6,5,2,1,7])
statistics.median_high(data)

4

In [3]:
x = [1.0, 3, 2, 4.5, 8.0]
x_with_nan = [1.0, 3, 2, math.nan, 4.5, 8.0]
x

[1.0, 3, 2, 4.5, 8.0]

In [15]:
statistics.multimode([20,15,12,17,18,15,20,20,15])

[20, 15]

In [4]:
x = [1.0, 3, 2, 4.5, 8.0]
statistics.mean(x)

3.7

In [2]:
x_with_nan = [1.0, 3, 2, math.nan, 4.5, 8.0]
statistics.mean(x_with_nan)

nan

In [3]:
x = [1.0, 3, 2, 4.5, 8.0]
x_with_nan = [1.0, 3, 2, math.nan, 4.5, 8.0]
x

[1.0, 3, 2, 4.5, 8.0]

In [4]:
statistics.mean(x_with_nan)

nan

In [5]:
np.nanmean(x_with_nan)

3.7

In [7]:
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_column

array([[1],
       [2],
       [3]])

In [8]:
a = np.array([1,2,3,4])
print ('Our array is:')
print (a)

Our array is:
[1 2 3 4]


In [9]:
np.mean(a)

2.5

In [12]:
a = np.array([[1,2],
              [3,4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
np.mean(a)

2.5

In [14]:
np.mean(a, axis=0)

array([2., 3.])

In [15]:
np.mean(a, axis=1)

array([1.5, 3.5])

In [16]:
a = np.array([1,2,3,4,5])
np.median(a)


3.0

In [17]:
a = np.array([1,2,3,4])
np.median(a)

2.5

In [18]:
a=np.array([[10,  7,  4],
            [ 3,  2,  1]])
np.median(a)

3.5

In [20]:
from scipy import stats

a = ([20,15,12,17,18,15,20,20])
stats.mode(a)

/tmp/ipykernel_235/2960305741.py:4: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(a)


ModeResult(mode=array([20]), count=array([3]))

In [24]:
# Computing the weighted mean
a=[5,2,7,2]
b=[1,2,3,4]
a,b = np.array(a), np.array(b)
wmean = np.average(a, weights=b)
wmean

3.8

In [25]:
wmean = np.average(c, weights=b)
wmean

6.0

In [3]:
data = pd.Series([10,5,2,6,7,8,4])
data.values

array([10,  5,  2,  6,  7,  8,  4])

In [5]:
data[4]

7

In [8]:
data = pd.Series([9.25, 10.5, 8.75, 1.3],
                 index=['w', 'x', 'y', 'z'])
data

w     9.25
x    10.50
y     8.75
z     1.30
dtype: float64

In [9]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [10]:
m = pd.Series([1,2,3,4])
statistics.mean(m)

2.5

In [11]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [14]:
covid_dict = {
    'Cebu':7800,
    'Manila':10000,
    'Davao': 8000,
    'Baguio': 6500,
    'Cavite': 2000
}
covid = pd.Series(covid_dict)
covid

Cebu       7800
Manila    10000
Davao      8000
Baguio     6500
Cavite     2000
dtype: int64

In [16]:
covid_dict = pd.DataFrame({'number of cases': covid })
covid_dict

number of cases
Cebu               7800
Manila            10000
Davao              8000
Baguio             6500
Cavite             2000

In [19]:
# Creating the dataframe
df = pd.DataFrame({"A":[1, 2, 3, 4, 5],
                   "B":[15, 12, 54, 13, 12],
                   "C":[2, 6, 7, 3, 8],
                   "D":[14, 23, 17, 21, 16]})

# Print the dataframe
df

A   B  C   D
0  1  15  2  14
1  2  12  6  23
2  3  54  7  17
3  4  13  3  21
4  5  12  8  16

In [20]:
df.mean()

A     3.0
B    21.2
C     5.2
D    18.2
dtype: float64

In [26]:
#Computes the mean along rows
df.mean(axis=0)
#Computes the mean along columns
df.mean(axis=1)


0     8.00
1    10.75
2    20.25
3    10.25
4    10.25
dtype: float64

In [27]:
# Creating the dataframe
df = pd.DataFrame({"A":[1, 2, 3, None, 5],
                   "B":[15, 12, 54, 13, 12],
                   "C":[2, 6, 7, None, 8],
                   "D":[None, 23, 17, 21, 16]})
# Print the dataframe
df

A   B    C     D
0  1.0  15  2.0   NaN
1  2.0  12  6.0  23.0
2  3.0  54  7.0  17.0
3  NaN  13  NaN  21.0
4  5.0  12  8.0  16.0

In [33]:
#Computing the median using pandas
#Median along rows
df.median(axis = 0)

A     2.5
B    13.0
C     6.5
D    19.0
dtype: float64

In [37]:
# Creating the dataframe
df = pd.DataFrame({"A":[1, 2, 3, None, 5],
                   "B":[15, 12, 54, 13, 12],
                   "C":[2, 6, 7, None, 8],
                   "D":[None, 23, 17, 21, 16]})

# Print the dataframe
df

A   B    C     D
0  1.0  15  2.0   NaN
1  2.0  12  6.0  23.0
2  3.0  54  7.0  17.0
3  NaN  13  NaN  21.0
4  5.0  12  8.0  16.0

In [42]:
df.median(axis = 0, skipna = True)

A     2.5
B    13.0
C     6.5
D    19.0
dtype: float64

In [44]:
pd.read_csv("/home/zenolucas/Desktop/SCHOOLING/dataAnalytics/SAMPLE.csv", skiprows=[2,4])

NAME  AGE  COURSE  YEAR
0        John Doe   20    BSIT     2
1       Juan Cruz   21    BSCS     3
2  Juan dela Cruz   20    BSCS     2
3  Filipinas Cruz   18  BSMKTG     1
4      Jane Perez   24    BSCE     4
5      Peter Grey   21    BSME     3
6     Joy de Leon   22    BSCS     2
7       Jan Perez   21    BSCS     3
8         Cris Uy   20    BSIT     2
9      Ben Santoa   22    BSIT     1

In [45]:
pd.read_csv("/home/zenolucas/Desktop/SCHOOLING/dataAnalytics/SAMPLE.csv", skiprows=[2,4])

NAME  AGE COURSE  YEAR
0        John Doe   20   BSIT     2
1  Juan dela Cruz   20   BSCS     2
2      Jane Perez   24   BSCE     4
3      Peter Grey   21   BSME     3
4     Joy de Leon   22   BSCS     2
5       Jan Perez   21   BSCS     3
6         Cris Uy   20   BSIT     2
7      Ben Santoa   22   BSIT     1

In [48]:
# reading a csv file
data = pd.read_csv("/home/zenolucas/Desktop/SCHOOLING/dataAnalytics/SAMPLE.csv")
data['AGE'].mode()

0    20
1    21
Name: AGE, dtype: int64

In [50]:
df = pd.DataFrame([
    [1, 2],
    [3, 4]],
    columns = ["a", "b"])
print(df)

   a  b
0  1  2
1  3  4


In [51]:
#find mean of column "b"
df_mean = df["b"].mean()
print(df_mean)

3.0
